### ISSUE TITLE
Dynamic menu confuguration

### ISSUE THREAD

**Issue by iddqd1** [otto-torino/django-baton#105]
Is it possible to build dynamic menu? For example list categories current user has right?

**Comment by iddqd1** [comment]
Easy answer is to edit and change app_list admin/base_site.html

**Comment by abidibo** [comment]
Hi @iddqd1 ,
at the moment the menu configuration is static because in the `settings.py` file.

If you need some logic, you can override the baton view: the `GetAppListJsonView` is responsible for returning a json object used to populate the sidebar menu. You can override it and declare the matching URL before baton include, see https://github.com/otto-torino/django-baton/blob/master/baton/views.py and https://github.com/otto-torino/django-baton/blob/master/baton/urls.py

**Comment by etanter** [comment]
Hi all,
I'm also facing this need. I've done what @abidibo suggests, and it seems to work fine.
Maybe it'd be better if `GetAppListJsonView` would expose a hook instead of hardcoding the call to `get_config('MENU')`. 
For instance, the corresponding line could be:
```
items = self.get_menu(request)
```
with a default implementation of `get_menu` that calls `get_config('MENU')`. 
Then our customizations would just need to override `get_menu`.
