### ISSUE TITLE
Extra whitespace on the right side in Django 3.1.2

### ISSUE THREAD

**Issue by farooqaaa** [otto-torino/django-baton#106]
There's an extra whitespace on the right side in Django 3.1.2.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/930117/97792960-1786ef80-1c07-11eb-86b5-51a32f8c6185.png)

The CSS code that causes is inside Django Admin's [nav_sidebar.css](https://github.com/django/django/blame/8ee4bb6ffcb3346c0fa8fb194986fbf9edadc822/django/contrib/admin/static/admin/css/nav_sidebar.css#L102) at line 102:

```
.main > #nav-sidebar + .content {
    max-width: calc(100% - 23px);
}

.main.shifted > #nav-sidebar + .content {
    max-width: calc(100% - 299px);
}
```

This can be easily fixed by adding `.content: { width: 100% !important}`

**Comment by abidibo** [comment]
Hi @farooqaaa , which baton version?

**Comment by farooqaaa** [comment]
I am on the stable version (1.12.1).

**Comment by abidibo** [comment]
@farooqaaa ,
actually, the demo app is on Django 3.1.2, and I saw the issue you're reporting, and it was caused by some CSS modifications due to the new Django sidebar menu, which now Baton disables, as you can see in this commit:

https://github.com/otto-torino/django-baton/commit/47112a0ba5f21334dc92926d73cd75f8d48d376f

Without this addition the problem is reproducible, but without it, I cannot reproduce it.

**Comment by farooqaaa** [comment]
That's great then. Thank you
