### ISSUE TITLE
Boolean field alingment may be more smooth 

### ISSUE THREAD

**Issue by AliPolat** [otto-torino/django-baton#112]
If two boolean fields are grouped together,  alingment of them slides a bit with respect to other fields. Such as these two fields "Invoice sent" and "Invoice paid";

without grouping
![pic1](https://user-images.githubusercontent.com/1778756/100447813-49825900-30c2-11eb-81a2-5a43ac1bcc4a.png)

with grouping together
![pic2](https://user-images.githubusercontent.com/1778756/100447824-4edfa380-30c2-11eb-89ea-d5a6640721d5.png)

Thank you..

**Comment by abidibo** [comment]
Yes, I know, I can do nothing about it. In the previous versions I kept the left alignment, but then we have problems if some error occurs because we cannot have a proper alignment of error messages. Wrapped fields are a nightmare to style properly, and unfortunately, this is the best I could do. The left spacing is dynamic and uses flex, so it's impossible to add a left margin to fix this issue.
