### ISSUE TITLE
First impressions (feedback & suggestions)

### ISSUE THREAD

**Issue by ppo** [otto-torino/django-baton#115]
Hi,  
I just discovered this project and so first, thank you 😀  
These are my first impressions after a few minutes playing with it… without really reading the documentation nor checking the closed issues, so sorry if things are not relevant.

### Bugs
- Fonts are not loaded because "/static/" is hardcoded but I configured "/s/".
- Hide the tooltip on `:active` (if not also `:hover`).

### Feature Requests
- Option to completely hide the footer.
- Option to not display gravatar at all. Or to use a field of the `User` model.
- Use the `MENU` configuration also to organize the home page. Or provide another option like `DASHBOARD`, which defaults to `MENU`.
- Allow to collapse blocks. Blocks are open by default but allow to define it as closed.

### Suggestions
- Reduce the size of the user block icons (view site, change password…). Probably also of the user's name. Are these so important to take so much real estate? 😉
- Use a different icon for `django.contrib.admindocs` (currently the same as "view site").
- Try to make the `MENU` configuration as simple as possible. (see example below)
  - Allow to define items as `app_name.model_name` (rather than using `apps` and `models`). And allow `app_name.*` to use all models.
  - Retrieve labels from `verbose_name[_plural]`.

**Example of simplified `MENU` definition:**
```
MENU = {
    "block title": ("app1.model1", "app1.model2", "app2.model1"),
    "section title": {
        "block title": ("app3.*",),
        "block title": (
            "app1.model3",
            ("rosetta", "named:rosetta-file-list?po_filter=project"),
            ("external link", "https://example.com/"),
        ),
    },
}
```

For the named URL, it will create the URL using `reverse(name, args=args, kwargs=kwargs)` by parsing `name?arg1&arg2&kwarg1=value`.  
I hope the rest is self explanatory, let me know if not 😉

**Comment by abidibo** [comment]
Hi @ppo ,

thank you for sharing your thoughts!

**Fonts are not loaded because "/static/" is hardcoded but I configured "/s/".**

Yeah, that's because I need to know the fonts paths at compilation time. See here:
 
https://github.com/otto-torino/django-baton/issues/81#issuecomment-661899608

**Hide the tooltip on :active (if not also :hover).**

There's no logic from Baton part about this. Baton just uses default bootstrap tooltips at the moment.

** Option to completely hide the footer. **

I can add this, even though it's as simple as adding a simple CSS rule in the base template.

** Option to not display gravatar at all. Or to use a field of the User model.**

The gravatar feature was added a few months ago' after a minor version release. Baton's face changed a lot after that release.
At the moment there is an option to collapse the user links in order to save some space. Again, in order to hide the gravatar, you can just add a CSS rule, but it's something I'll look into, since does not break things.

Using a field of the user model could be done, but requires an async operation because I don't want to override templates if I can.
 
** Use the MENU configuration also to organize the home page. Or provide another option like DASHBOARD, which defaults to MENU.**

We thought a lot about the admin index page. I really don't like the index page containing all apps models and links, especially because having a sidebar menu makes it somewhat unuseful. I always override the admin index page per site, showing statistics or some custom content related to webapp.

** Reduce the size of the user block icons (view site, change password…). Probably also of the user's name. Are these so important to take so much real estate?**

UI/UX is going in that direction, all big and clear. Anyway, with this option `COLLAPSABLE_USER_AREA` you can collapse these links.

** Use a different icon for django.contrib.admindocs (currently the same as "view site").**
We'll definitely address this soon

** Try to make the MENU configuration as simple as possible **

Yes, good hints. We should definitely make the menu configuration less verbose. Not too much since we nee dictionaries to specify perms and other stuff, but we may find the right syntax to address app and model voices, and some shortcuts it no further customization is needed. This is a breaking change though, and we'll probably consider it in Baton v2, whose development will begin as soon as bootstrap 5 will reach a beta version.


Thank you very much for all your suggestions. Bye!
