### ISSUE TITLE
add django-admin-rangefilter to default baton?

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#123]
Currently the base django admin filter of days/months ago is not that useful. It's possible to add https://github.com/silentsokolov/django-admin-rangefilter to the default baton? because i tried this package with baton and it worked great. Would be nicer if it already in baton 😄

**Comment by abidibo** [comment]
Yeah, I thought about it, I also use that package. But I'm not sure about it, I mean, the package is currently well maintained, and they can focus on it. While if I put it in Baton, I'll probably leave it at its current state because I've many other developments to follow. Until now I've added packages which were not implemented anymore. What I can say is that if for any reason the django-admin-rangefilter team will stop supporting the package, I'll surely fork it and keep it alive, maybe also integrate it in Baton directly.

**Comment by linhnvhicts** [comment]
ok thank you for the answer 👍
