### ISSUE TITLE
__str__ in Inlines

### ISSUE THREAD

**Issue by AlanL-django** [otto-torino/django-baton#138]
Firstly, let me say thank you for your work on Baton. It looks like it could be the open source, actively maintained Suit replacement that I've been looking for for a couple of years now.

I'm encountering one problem that I can't find how to configure or fix: in a TabularInline, no matter what I do or don't put in the fields list, the __str__() of the model is being shown in addition to the model's database fields.

If there is a configuration to prevent this I haven't found it in the documentation.

Django==3.1.7
django-baton==2.1.3

**Comment by abidibo** [comment]
Hi @AlanL-django ,

thank you.

Yeah, I know what you're talking about. Actually, also default Django admin shows that ('avatar' is the model __str__):

![Screenshot from 2021-03-02 14-56-53](https://user-images.githubusercontent.com/444093/109659448-f956df00-7b67-11eb-8ad0-bbf79dac62f9.png)

I personally don't like it very much, in fact, the first Baton releases used to hide it, see #5 .
The problem is that inlines have a `show_change_link` [option](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link). When set to `True` (and the inline model is registered to admin) an edit icon appears near the model string representation as you can see in the prev screenshot.

This is why I had to add it back, essentially.

In any case, it's quite easy to get rid of it, just override, or extend the Baton admin `base_site.html` template (I always do), and add the following style block:

```
<style type="text/css" media="screen">
.inline-related .original {
    display: none;
}
</style>
```

**Comment by AlanL-django** [comment]
Excellent! Thank you
