### ISSUE TITLE
form tabs for generic relation

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#151]
Hi @abidibo,

I'm struggling to place an inline in a separate tab (either standalone, or as part of a group).
The specificity here is that the field is defined by a generic relation, not a standard foreign key.
```
  docs = GenericRelation(Document, ...)
```
I've tried both `inline-document` and `inline-documents` as part of the class name (as in `baton-tab-inline-documents`), but no luck.

What am I missing?

Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,
Baton tabs engine acts on inlines by searching for their wrapping element id in the DOM. Normally it is:
```
[RELATED_NAME]-group
```

but for generic relations it's quite different. In any case is still possible to get them work:

![Screenshot from 2021-04-27 09-42-41](https://user-images.githubusercontent.com/444093/116204897-7d2ee100-a73d-11eb-9575-d0e2be433feb.png)

In this example:

**models**

``` python
class Activity(models.Model):
    FAVORITE = 'F'
    LIKE = 'L'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=1, choices=ACTIVITY_TYPES)
    date = models.DateTimeField(auto_now_add=True)

    # mandatory fields for generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

class News(models.Model):
    title = models.CharField('title', max_length=50, help_text='please insert a cool title')
    # ...
    favorites = GenericRelation(Activity)
```

**admin**

``` python
class ActivitiesInline(GenericStackedInline):
    model = Activity
    extra = 1

@admin.register(News)
class NewsAdmin(admin.ModelAdmin):
    list_per_page = 2
    list_display = (
        'title',
        # ...
    )
    inlines = [AttachmentsInline, VideosInline, ActivitiesInline, ]

    fieldsets = (
        ('Dates', {
            'fields': ('date', 'datetime', ),
            'classes': ('order-1', 'baton-tabs-init', 'baton-tab-fs-content', 'baton-tab-fs-flags', 'baton-tab-group-fs-attachments--inline-attachments', 'baton-tab-group-fs-videos--inline-videos', 'baton-tab-inline-news-activity-content_type-object_id'),
            'description': 'This is a description text'
        }),
       # ...
    )
```

As you can see, I used the `ActivitiesInline` which is a `GenericStackedInline`, and the magic string to use for the baton inline class is: `baton-tab-inline-news-activity-content_type-object_id`, that is because the "related name" is `news-activity-content_type-object_id`. And you can see it in the screenshot, that is the original `#id` that django admin gives to the wrapping element followed by `-group`.

So I don't know exactly what you should put in your case, because I don't know all the models involved, but following the same rules you should be able to get it.

Let me know if it helps, bye!

**Comment by etanter** [comment]
Thanks @abidibo for the detailed explanation, it works as expected!
