### ISSUE TITLE
collapsible tabular inline?

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#156]
Hi @abidibo,

Would it be possible to add a way to make tabular inlines collapsible?

Thanks!

**Comment by abidibo** [comment]
I'll look into it soon

**Comment by abidibo** [comment]
This is quite tricky. The whole fieldset can be collapsed, but make collapsable every single row is hard. With stacked inlines, we have a header that can be used as a toggle and that is always visible. We don't have such a thing in tabular inlines. If I collapse a row, then there's no info left about it still visible. And if I keep something visible injecting it into the DOM (and should be a new table row) I don't get the point of collapsing it since I take space the same.

I've not ideas about addressing this, maybe you've something in mind and could explain better, with some edited screens or something like that.

**Comment by etanter** [comment]
Oh, I was thinking of making the whole tabular collapsible, with the title as handle to show/hide (just like a collapsible fieldset).

**Comment by abidibo** [comment]
Shouldn't that just be possible by settings `classes = ('collapse', )` in the `TabularInline` ?

**Comment by etanter** [comment]
I don't understand why, but adding `classes = ('collapse', )` in the tabular inline does not work.
Additionally, it would be better to make the decision of the inline being collapsible or not in the enclosing admin.

**Comment by abidibo** [comment]
![Screenshot from 2021-05-14 17-06-23](https://user-images.githubusercontent.com/444093/118290479-c66d8780-b4d6-11eb-88ff-97e300092058.png)
![Screenshot from 2021-05-14 17-06-17](https://user-images.githubusercontent.com/444093/118290487-c8374b00-b4d6-11eb-8d0d-ca7964e865fb.png)

In my demo app I can collapse tabular inlines

**Comment by etanter** [comment]
it was a problem with my overriding of the tabular admin template... sorry (again) about the noise!
