### ISSUE TITLE
django-baton not usable with django 4.0

### ISSUE THREAD

**Issue by brocasm** [otto-torino/django-baton#197]
i can't use django-baton with django v4.0  
Some deprecated and removeved code functions

**Comment by abidibo** [comment]
Hi @brocasm ,

yeah, the current official release it's still not compatible. Btw you can install the dev branch, which supports Django 4.0.

I've to wait a bit before merging because I've got a lot of tests that depend on third party packages that still does not support Django 4.0. Also the included testapp suffer from the same problem. I'll wait a bit and then if the problem persist I'll drop these dependencies.

**Comment by abidibo** [comment]
An update on this one, I'm still waiting django-filer to become compatible with Django 4

**Comment by MathiasKowoll** [comment]
Hi @abidibo any updates, Im not pushing in any way but somehow I'm kinda desperate to try Django 4 ;)

**Comment by abidibo** [comment]
Hi @MathiasKowoll, @brocasm I finally decided to drop the dev/test dependency on django-filer. I've just released Baton 2.3.0 which adds support to Django 4.0.
