### ISSUE TITLE
Update Google Analytics to work with GA4, which doesn't use the view_id

### ISSUE THREAD

**Issue by Nick-foote** [otto-torino/django-baton#247]
GA Universal Analytics property is being depreciated, which has the `view_id` required for Google Analytics in Baton.

> "Universal Analytics properties will stop collecting data starting 1 July 2023. It’s recommended that you create a Google Analytics 4 property instead."

This means any new GA properties won't link with the Baton admin

**Comment by abidibo** [comment]
Yeah, the problem is the js library by google doesn't work anymore, and I haven't found  a new version of it. I'm not willing to provide this functionality through API's, also because we are now using other analytics providers internally, so I'll probably remove the analytics package and the functionality itself.

**Comment by abidibo** [comment]
Analytics module was remove in v3.0.0
