### ISSUE TITLE
Page flashes on every reload

### ISSUE THREAD

**Issue by toodamfilthy** [otto-torino/django-baton#50]
Whenever I click a link the whole page flashes to display whatever as clicked.

**Comment by abidibo** [comment]
The "flash" you see is just a hide/show body effect. The fact is that the sidebar menu is injected in the dom, and the whole layout adjusted to support it. During these operations the body is hidden, otherwise, you would see containers moving around. When injection ends, then the body is shown again.
It's not a bug, it's intended.
