### ISSUE TITLE
whole page flashes on each link

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#66]
Hi,
Each time I click on a different menu item, the whole page (including banner, menu, etc.) briefly flashes white and then back. It's quite disturbing to the eye, especially when one is clicking around looking for information. 
I could send a small video if that helps demonstrating the problem.
Any idea what is causing this, and how to fix it?
Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

this is an intended and expected behaviour. The reason for it is that baton has to move divs around in order to inject the menu, the form tabs and so on..., so you would see weird stuff, i.e. the sidebar menu appearing from the left side moving the content to right. In order to prevent this, the whole document is hidden (opacity 0) until baton finishes its work, and then unhidden (opacity 1).

If you use the always collapsed menu, then maybe you can try to add this style (overriding baton admin base_site.html template)

```
<style>
body {
  opacity: 1 !important;
}
</style>
```

**Comment by etanter** [comment]
Thanks for the opacity "fix". It flashes less, and I like that, but it still does in some cases. 
Is there a way to turn it off more globally? (in the worst case if it's not nice, I'll leave it as is)
