### ISSUE TITLE
darker reload flash

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#68]
Hi, 
Related to #66: I now see what you meant with seeing the page being constructed, which I agree is not very nice either.
Now, the flash is aggressive on the eye because it goes to white. Would it be possible to get the flash to go to black/grey instead?
Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,

that's quite easy indeed, you can choose the colour from which to fade in: 

```
<style>
html {
  background: #37474f;
}
</style>
```
The problem at the moment is that you'll see the HTML background in the login screen, but in the next release (probably today) I'll fix that.

In the beginning, I was thinking about placing some sort of spinner, but then I decided not to do it because I should have forced a minimum interval of time (otherwise you neither see it), causing a delay in the page load.

**Comment by abidibo** [comment]
You can also control the transition interval:

```
body {
  transition: opacity 0.5s ease !important;
}
```

**Comment by etanter** [comment]
Hi @abidibo 

Excellent, changing the background color smoothens the effect of the transition quite a lot.

Thanks again for your responsiveness, much appreciated!
