### ISSUE TITLE
Allow font to be changed in baton config

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#92]
Hi i know that i can change the font of baton following this step https://github.com/otto-torino/django-baton/issues/45
But it's kinda hard on step 2 to navigate to the css file (especially on virtual env). 
Would be nice to just set the font by name in the baton config 😄

**Comment by abidibo** [comment]
Hi @linhnvhicts ,
this isn't something I'll introduce, because the font configuration is CSS stuff, too bad to apply the rule through javascript. As it is CSS stuff, I cannot set a runtime variable to handle this. There would be 2 possibilities here:

- apply the font rule through js (I don't like it)
- insert a style block in the template as per the method 1 of #45 

This second possibility is something that can be super easily done outside baton, for example, I always override the `admin/base_site.html`, defining it in an application listed before baton in the installed apps.

**Comment by linhnvhicts** [comment]
@abidibo I got it thank you for explaining, i will follow step 1 of that to change the font
