### ISSUE TITLE
Filtered lists are truncated

### ISSUE THREAD

**Issue by blemoine167** [otto-torino/django-baton#93]
Hello,

In a django 3 application, after following your configuration directives, i have a problem with the display of model lists. A css rule is still applied : 
<img width="1075" alt="Capture d’écran 2020-09-07 à 09 01 39" src="https://user-images.githubusercontent.com/7974584/92357809-c1a33900-f0e8-11ea-9421-d928dff58b79.png">

The margin is truncating the list, hiding the last columns.
Did i miss something ? 

<img width="404" alt="Capture d’écran 2020-09-07 à 09 06 24" src="https://user-images.githubusercontent.com/7974584/92358218-7a697800-f0e9-11ea-9027-75c5c0a96a01.png">

**Comment by abidibo** [comment]
Hi @blemoine167 ,

I cannot reproduce this bug. The problem here seems to be the following: when asking for `admin/changelists.css` file, the one served is not the one included in Baton. That's weird, because as I can see from your `INSTALLED_APPS` baton id correctly defined before the `django.contrib.admin` application. 
Have you got some other `changelists.css` files in other apps? Maybe a path problem? Can you provide me the full path to this css file?

**Comment by blemoine167** [comment]
Hello,

thank you for your answer, i did override the css rule with my own css but now... when i remove my override i cannot reproduce the bug. Maybe it was some cache glitch... Sorry for the disturbance. All is working well now.
